projects:
  flashapi:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/app/models/amplify.ts
        docsFilePath: src/graphql
        graphQLApiId: kzoeujandbasppt2iv4g44smua
      endpoints:
        prod: >-
          https://3jm6orqaofcglmbt3kno44mh2q.appsync-api.us-east-1.amazonaws.com/graphql
